# RTL and Testbench File List
# Generated by 'make update_list'
# Date: Thu Sep  4 17:49:06 EEST 2025
# Project: FIFO_lib

# RTL Source Files
/home/moazk/nano/FIFO_lib/sources/rtl/STD_MODULES.v
/home/moazk/nano/FIFO_lib/sources/rtl/sync_fifo.sv

# Testbench Files
/home/moazk/nano/FIFO_lib/sources/tb/simple_sync_fifo_tb.sv
