# RTL and Testbench File List
# Generated by 'make update_list'
# Date: Fri Sep  5 14:44:34 EEST 2025
# Project: FIFO_lib

# RTL Source Files
/home/moazk/nano/FIFO_lib/sources/rtl/STD_MODULES.v
/home/moazk/nano/FIFO_lib/sources/rtl/sync_fifo.sv

# Testbench Files
/home/moazk/nano/FIFO_lib/sources/tb/sync_fifo_tb.sv
